### ISSUE TITLE
Crash on startup, java 22 isnt supported

### ISSUE THREAD

**Issue by Homtaro** [brentmaas/BuildGuide#3]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Java HotSpot(TM) 64-Bit Server VM' (java) 22 with version 21.
More details:
	 - Mod 'Build Guide' (buildguide) 0.4.1 requires version 21 of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 22!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by brentmaas** [comment]
Hi, thanks for letting me know!

I've also run into that, so I've already fixed it in https://github.com/brentmaas/BuildGuide/commit/b241ea935a67e56ddef99cd812d9a4a72f6ea2c2. That fix hasn't been released yet, so I'll keep the issue open and I'll let you know when I've released it. The next release should be soon after I fix a small issue I've found while testing.

With a bit of technical know-how, you can also make a hotfix yourself: you can take the file `fabric.mod.json` in the jar file and change the value of `java` from `21` to `>=21`. That should allow the mod to work with Java 22.

**Comment by brentmaas** [comment]
It should be fixed in 0.4.2!
